name: CI/CD Pipeline - Student Crud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven
      - name: Build project with Maven
        run: mvn clean package -DskipTests

      # Step 4: Upload JAR artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: student-service-jar
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout again
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/student-crud:latest .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/student-crud:latest
